target-version = "py312"
line-length = 100
src = ["src", "dags", "tests"]
extend-exclude = ["infra/.terraform"]

[lint]
select = ["ASYNC", "B", "D", "E", "F", "I", "SIM", "UP"]

[lint.per-file-ignores]
"tests/**/*.py" = ["D"]

[lint.pydocstyle]
convention = "google"

[format]
docstring-code-format = true
indent-style = "space"
line-ending = "auto"
quote-style = "double"

